import {
  Bell, ChartNoAxesCombined, ClipboardList, CreditCard, FileText, Globe2, LayoutDashboard,
  Megaphone, MessageSquare, Package, Settings, ShieldCheck, Star, Tags, Truck, Users,
} from 'lucide-react'

export const nav = [
  ['Dashboard', '/dashboard', LayoutDashboard],
  ['Products', '/products', Package],
  ['Categories', '/categories', Tags],
  ['Orders', '/orders', ClipboardList],
  ['Customers', '/customers', Users],
  ['Coupons', '/promotions/coupons', Megaphone],
  ['Flash Sales', '/promotions/flash-sales', Megaphone],
  ['Banners', '/promotions/banners', Megaphone],
  ['Affiliate', '/promotions/affiliate', Megaphone],
  ['Payments', '/payments', CreditCard],
  ['Shipping', '/shipping', Truck],
  ['Returns', '/shipping/returns', Truck],
  ['Reviews', '/reviews', Star],
  ['Tickets', '/support/tickets', MessageSquare],
  ['Live Chat', '/support/live-chat', MessageSquare],
  ['FAQ', '/support/faq', MessageSquare],
  ['Notifications', '/notifications', Bell],
  ['Reports', '/reports', ChartNoAxesCombined],
  ['SEO', '/seo', Globe2],
  ['Blog', '/blog', FileText],
  ['Settings', '/settings', Settings],
  ['Admins', '/settings/admins', ShieldCheck],
  ['Audit Log', '/settings/audit-log', ShieldCheck],
]

export const resourceMap = {
  '/products': { title: 'Products', endpoint: '/products', create: '/products/create', columns: ['name', 'sku', 'price', 'stock', 'status'] },
  '/categories': { title: 'Categories', endpoint: '/categories', columns: ['name', 'slug', 'isActive', 'sortOrder'], sample: { name: 'New category', slug: 'new-category', parentId: null, imageUrl: '', sortOrder: 0, isActive: true } },
  '/orders': { title: 'Orders', endpoint: '/orders', columns: ['code', 'customerName', 'status', 'paymentStatus', 'totalAmount'] },
  '/customers': { title: 'Customers', endpoint: '/customers', columns: ['fullName', 'email', 'status', 'segment', 'loyaltyPoints'] },
  '/promotions/coupons': { title: 'Coupons', endpoint: '/promotions/coupons', columns: ['code', 'discountType', 'discountValue', 'usageLimit', 'status'], sample: { code: 'SALE10', discountType: 'Percentage', discountValue: 10, usageLimit: 100, status: 'Active', startsAtUtc: null, endsAtUtc: null } },
  '/promotions/flash-sales': { title: 'Flash Sales', endpoint: '/promotions/flash-sales', columns: ['name', 'categoryId', 'discountPercent', 'status'], sample: { name: 'Weekend sale', categoryId: null, discountPercent: 15, status: 'Draft', startsAtUtc: new Date().toISOString(), endsAtUtc: new Date(Date.now() + 86400000).toISOString() } },
  '/promotions/banners': { title: 'Banners', endpoint: '/promotions/banners', columns: ['title', 'position', 'status'], sample: { title: 'Homepage banner', imageUrl: 'https://example.com/banner.jpg', linkUrl: '/', position: 'homepage', status: 'Draft', startsAtUtc: null, endsAtUtc: null } },
  '/promotions/affiliate': { title: 'Affiliate', endpoint: '/promotions/affiliate', columns: ['partnerName', 'trackingCode', 'commissionPercent', 'status'], sample: { partnerName: 'Partner', trackingCode: 'PARTNER01', commissionPercent: 5, status: 'Active' } },
  '/payments': { title: 'Payments', endpoint: '/payments', columns: ['transactionCode', 'method', 'status', 'amount', 'refundedAmount'] },
  '/shipping': { title: 'Shipping Configs', endpoint: '/shipping/configs', columns: ['region', 'minWeightKg', 'maxWeightKg', 'fee', 'isActive'], sample: { region: 'Ho Chi Minh', minWeightKg: 0, maxWeightKg: 5, fee: 30000, isActive: true } },
  '/shipping/returns': { title: 'Returns', endpoint: '/shipping/returns', columns: ['orderId', 'customerId', 'reason', 'status'], sample: { orderId: '', customerId: '', reason: 'Customer request', status: 'Requested', resolutionNote: '' } },
  '/reviews': { title: 'Reviews', endpoint: '/reviews', columns: ['productId', 'customerName', 'rating', 'status', 'isFlagged'] },
  '/support/tickets': { title: 'Tickets', endpoint: '/support/tickets', columns: ['subject', 'customerEmail', 'status', 'priority', 'assignedTo'], sample: { subject: 'Need help', customerId: '', customerEmail: 'customer@example.com', priority: 'Medium', message: 'Describe the issue' } },
  '/support/faq': { title: 'FAQ', endpoint: '/support/faq', columns: ['question', 'category', 'isPublished', 'sortOrder'], sample: { question: 'Question', answer: 'Answer', category: 'General', isPublished: true, sortOrder: 0 } },
  '/notifications': { title: 'Notifications', endpoint: '/notifications', columns: ['title', 'audience', 'recipientId', 'isRead'], createEndpoint: '/notifications/push', sample: { title: 'Notice', message: 'Message', audience: 'Admin', recipientId: null } },
  '/seo': { title: 'SEO Meta', endpoint: '/seo/meta', columns: ['entityType', 'entityId', 'metaTitle', 'slug'], sample: { entityType: 'page', entityId: 'home', metaTitle: 'Home', metaDescription: 'Homepage', slug: 'home' } },
  '/blog': { title: 'Blog Posts', endpoint: '/blog/posts', columns: ['title', 'slug', 'status'], sample: { title: 'New post', slug: 'new-post', content: '<p>Content</p>', status: 'Draft' } },
  '/settings/admins': { title: 'Admins', endpoint: '/settings/admins', columns: ['email', 'fullName', 'role'], sample: { email: 'staff@labstore.local', fullName: 'Staff Admin', password: 'Admin@123456', role: 'Staff', isActive: true } },
  '/settings/audit-log': { title: 'Audit Log', endpoint: '/settings/audit-log', columns: ['adminUserId', 'action', 'ipAddress', 'createdAtUtc'] },
}
